### ISSUE TITLE
Hot reload react

### ISSUE THREAD

**Issue by josephriosIO** [Devtography/electron-react-typescript-webpack-boilerplate#13]
a hot reloader would be amazing

**Comment by iamWing** [comment]
> a hot reloader would be amazing

Do you mean to auto reload the main process? Coz I believe the renderer process is already reloadable if you use the command `npm run dev` to start Webpack in development mode. You just need to refresh the page in your electron app whenever you've changed something for the renderer process once the app is started.

**Comment by miuan** [comment]
> Do you mean to auto reload the main process? Coz I believe the renderer process is already reloadable if you use the command `npm run dev` to start Webpack in development mode. You just need to refresh the page in your electron app whenever you've changed something for the renderer process once the app is started.

that would be nice if the refresh is done automatically, or if is possible on `npm run dev` be on some special url where the hot reaload will works, webpack providing a devServer for this purposes https://webpack.js.org/configuration/dev-server/

**Comment by iamWing** [comment]
> > Do you mean to auto reload the main process? Coz I believe the renderer process is already reloadable if you use the command `npm run dev` to start Webpack in development mode. You just need to refresh the page in your electron app whenever you've changed something for the renderer process once the app is started.
> 
> Hi! That would be nice if the refresh is done automatically, or if is possible on `npm run dev` be on some special url where the hot reaload will works, webpack providing a devServer for this purposes https://webpack.js.org/configuration/dev-server/
> 
> but good job anyway!

Okay I got what you mean now. Right now the dev server is not being invoked on neither the commands included in this project. I'm not sure if the dev server works with electron apps or not but I'll give it a try later when I have time. Meanwhile you may wanna implement that yourself, as I'm pretty busy recently and not sure when I'll be able to do more development on this boilerplate, so a pull request is very much welcome.

My initial thoughts on how would be you config the dev server options in `webpack.config.js`, then edit the `npm run dev` command in `package.json` to invoke the dev server by calling `npx webpack serve`. You may wanna give it a try.
