### ISSUE TITLE
Importing in renderer.tsx another tsx file gives me a blank window

### ISSUE THREAD

**Issue by raphael10-collab** [Devtography/electron-react-typescript-webpack-boilerplate#14]
If in renderer.tsx I substitute the content with: 

renderer.tsx : 

    import '../app';

src/app : 

    import React from 'react';
    import ReactDOM from 'react-dom';
    import App from './components/App';
    import './styles/index.less';

    ReactDOM.render(<App />, document.getElementById('app'));

src/app/components/App.tsx : 

    import React, { useState, useEffect } from 'react'

    function App() {
      return (
        <div className='container'>
          <h2 className='heading'>
              Multiple Selective Windows Communication
          </h2>
        </div>
      );
    }

src/app/styles/index.less :  

    @import './variables.less';

    html,
    body,
    #app {
      height: 100%;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica,
        Arial, sans-serif;
      margin: auto;
      max-width: 38rem;
      color: @color-text;
      background-color: @color-body-bg;
    }

    button {
      background-color: @color-button-bg;
      color: @color-text;
      border: none;
      padding: @padding-normal;
      border-radius: @radius-normal;
      font-size: @text-normal;
      outline: none;
      min-width: 10rem;
    }

    button:hover {
      filter: brightness(120%);
    }
    button:active {
      filter: brightness(110%);
    }

    #app,
    .heading {
      display: flex;
      align-items: center;
    }

    h2,
    p {
      font-weight: 400;
      line-height: 1.5;
    }

    .heading {
      color: #65bb82;
      margin-bottom: 2rem;
    }

    .teaser {
      color: #99beca;
      background: #00000030;
      padding: 0.5rem 1rem;
      border-radius: 4px;
    }

    .version {
      color: #80b99c;
      &s {
        margin-top: 2rem;
      }
    }

/src/app/styles/variables.less :  

     // Colors 
     @color-dark: #1f1f1f;
     @color-input-bg: #1d1d1d;
    @color-body-bg: #242424;
    @color-button-bg: #404040;
    @color-text: #d8d8d8;

    // Sizes & Measurement
    @base-font-size: 16px;
    @radius-normal: 0.25rem;
    @padding-normal: 0.75rem;
    @text-normal: calc(1rem - 2px);

    // Miscellaneous
    @base-font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
      Helvetica, Arial, sans-serif;

I get a blank window, instead of a window with "Multiple Selective Windows Communication" heading 

![image](https://user-images.githubusercontent.com/70313067/107560232-65839a00-6bdd-11eb-9fc0-4f77f55d1707.png)

The same if I do in renderer.tsx :  

    import React from 'react';
    import ReactDOM from 'react-dom';
    import App from '../app/components/App';

    ReactDOM.render(
      <App />,
      //<div className="app">
        //<h4>Welcome to React, Electron and Typescript</h4>
        //<p>Hello</p>
      //</div>,
      document.getElementById('app'),
    );

I "solved" the problem by substituting in /src/app/components/App.tsx :  

    //import React, { useState, useEffect } from 'react';
    import * as React from 'react';

But I do not understand why ....

**Comment by ozntel** [comment]
I just had the same problem. As you mentioned, importing react as below solves the issue:

```ts
import * as React from 'react';
```

Somehow `import React from 'react'` doesn't work.

**Comment by iamWing** [comment]
> I just had the same problem. As you mentioned, importing react as below solves the issue:
> 
> ```ts
> import * as React from 'react';
> ```
> 
> Somehow `import React from 'react'` doesn't work.

Possibly something related to default export if `import * from 'react'` works but not `import React from 'react'`. I'm doing a major update for this repo to get everything up to date atm. Will also try tackle this issue in the next update.
