### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by Reldey** [Devtography/electron-react-typescript-webpack-boilerplate#2]
Readme states to use 'npm run install' however there is no 'install' method defined in package.json. Should be just 'npm install'.

**Comment by marcusjwhelan** [comment]
Also, maybe this is just me but dev only builds the project. I have to run start to get the application to show up.

**Comment by jkhaui** [comment]
@Devtopgraphy please fix the documentation if you're gonna keep it as an open-source repo, it takes like 2 seconds to correct. I nearly turned away from using this because I assumed it had bugs like so many of the other electron/react boilerplates

**Comment by iamWing** [comment]
> Also, maybe this is just me but dev only builds the project. I have to run start to get the application to show up.

No it's not just you, it's designed to work in this way. The `npm run dev` command starts a watcher process in your terminal to monitor the changes made in the source code and performs live rebuild on code modified. You'll need to run `npm start` in an separate CLI instance if you wanna get the application show up.

**Comment by iamWing** [comment]
> @Devtopgraphy please fix the documentation if you're gonna keep it as an open-source repo, it takes like 2 seconds to correct. I nearly turned away from using this because I assumed it had bugs like so many of the other electron/react boilerplates

Mate, sorry for the late reply, my schedule was awfully full over the last couple months. I'll have the doc fixed alongside with some dependencies updates likely in this weekend, but maybe next time you can help fixing the issue and make a pull request so the issue can be fixed asap? Thanks.

**Comment by iamWing** [comment]
6a5b75b97fe0fed99652791fae1661bd1d6a6420 has addressed the issue. I'm closing this for now.
