### ISSUE TITLE
Broken on Windows 11 WSL 2 

### ISSUE THREAD

**Issue by rishabh-bector** [Devtography/electron-react-typescript-webpack-boilerplate#29]
Used this template in something I started a few months ago, and it works great. I updated to Windows 11 a few days ago, and now none of my apps render properly. I've been trying to get to the bottom of it, but haven't yet. This template is also affected, although the issue is probably only relevant for devs who use WSL 2.

**Comment by iamWing** [comment]
Hi @rishabh-bector, can you list out the details of your dev environment? And were you building Windows app or for other platforms? 

I haven't used the template with WSL before but am planning to do so for another project soon, so I'll spend some time to see what causes the issue. It's likely to take me some time to do so tho, and I'm not on Windows 11 yet.

Also can you try update the `electron` package to newest version and see if it helps? It could be Windows 11 broke something.
