### ISSUE TITLE
Question - Live Reload

### ISSUE THREAD

**Issue by sebinq** [Devtography/electron-react-typescript-webpack-boilerplate#3]
Hello I would like to ask if there is any possibility to make Live Reload work? Or is it already working and I am just not able to use it? Thanks.

Btw thank you very much for this boilerplate it saves a lot of time for me!

**Comment by iamWing** [comment]
Do you mean live reload / auto refresh on the app UI?

Currently the compiler isn't able to trigger auto refresh on UI changes yet, but can auto recompiles the source code on change if you run the `Webpack` in development mode with command `npm run dev`.

You'll be able to see your changes by refreshing the app UI like how you refresh a webpage in Chrome once the auto recompile is completed.

**Comment by iamWing** [comment]
I'll close this issue for now just to keep things clean. Simple open another issue if you still got questions. Thanks.
