### ISSUE TITLE
UI shows nothing

### ISSUE THREAD

**Issue by MotionPhix** [Devtography/electron-react-typescript-webpack-boilerplate#5]
After running npm start, the ui doesn't show anything... The window opens but nothing gets displayed. No errors, nothing. How could this be resolved?

**Comment by iamWing** [comment]
Have you run `npm run dev` before running `npm start`? You should be able to see the following once the app window opened. 
<h4>Welcome to React, Electron and Typescript</h4>
<p>Hello</p>

**Comment by MotionPhix** [comment]
I did that and still nothing shows up. I tried running `npm run dev` in a separate terminal (command line) and `npm start` in another one but still nothing shows up

**Comment by xandao6** [comment]
Are you using windows 7?

**Comment by MotionPhix** [comment]
Nope. Windows 10

**Comment by iamWing** [comment]
I've made the `3.0.0` release and tested on both my Mac and Windows machines. It should work just fine. I'll close this issue for now. Do open another issue if you still have the same problem and we can look into that. Thanks.
