### ISSUE TITLE
Synthetic imports

### ISSUE THREAD

**Issue by Alkanores** [Devtography/electron-react-typescript-webpack-boilerplate#6]
Hello, I create my app with your boilerplate, but I can't write imports like:
```
import React from 'react';
import styles from 'random.module.css'
```

instead of this I **_must_** write import like:
```
import * as React from 'react';
import * as styles from 'random.module.css';
```

Why I can't add imports like first variant?

**Comment by LHY-iS-Learning** [comment]
try add 
    `"esModuleInterop": true`
to tsconfig.json
it works for me

**Comment by Alkanores** [comment]
Yes, it works, thanks)
